\ GENERATED BY gen-x.f
include cross.f
hex
8074 textaddr !
518 textsize !
1058c pdictaddr !
10924 dictbase !
99c6a0 theaptop !
74 constant textoffset
create .text textsize @ allot align
.text textsize @ textoffset load.text boot/ff-arm
81dc c:(variable) !
81ec c:(constant) !
80bc c:(:) !
84e0 c:(deferred) !
here pdictbase !
810c pnative @
8118 pnative !
812c pnative c@
8138 pnative c!
8184 pnative fsread
819c pnative fswrite
81b4 pnative fsseek
8158 pnative fsopen
8174 pnative fsclose
81cc pnative mmap
814c pnative halt
80b0 pnative clear
80a4 pnative reset
13294 pconstant h
13298 pconstant dp
822c pnative exit
81fc pnative (literal)
820c pnative (sliteral)
8238 pnative (do)
8250 pnative (loop)
8284 pnative (+loop)
8294 pnative r@
82b4 pnative r>
82a4 pnative >r
82c4 pnative i
82d4 pnative j
82e4 pnative +
82f4 pnative -
8304 pnative *
80f0 pnative (if)
80e4 pnative (else)
8314 pnative /mod
8390 pnative u/mod
83d4 pnative and
83e4 pnative or
83f4 pnative xor
8404 pnative swap
8418 pnative drop
8424 pnative dup
8430 pnative over
8440 pnative =
845c pnative >
8478 pnative <
132a0 pconstant tib
8494 pnative s@
84a4 pnative lshift
84b4 pnative rshift
84c4 pnative rshifta
84d4 pnative execute
84e8 pnative unloop
84f4 pnative cmove
8520 pnative cmove>
c:(variable) @ pnative (variable)
c:(constant) @ pnative (constant)
c:(:) @ pnative (:)
80cc pnative (does)
1329c pconstant heaptop
8074 pconstant _start
858c pconstant _end
8554 pnative cas
here plastprim !
c:(deferred) @ pnative (deferred)
here pdictbase @ - pdictsize !
pddp @ preloc initmdp
mdictbase @ dictbase @ - dictoffset !
99e69c stackbase !
decimal
