\ GENERATED BY gen-x.f
include cross.f
hex
8048080 textaddr !
398 textsize !
8049418 pdictaddr !
80497b0 dictbase !
89d552c theaptop !
80 constant textoffset
create .text textsize @ allot align
.text textsize @ textoffset load.text boot/ff-i386
80481be c:(variable) !
80481cb c:(constant) !
80480c5 c:(:) !
80483b9 c:(deferred) !
here pdictbase !
804810d pnative @
8048118 pnative !
8048124 pnative c@
8048133 pnative c!
804816f pnative fsread
8048183 pnative fswrite
8048197 pnative fsseek
8048149 pnative fsopen
804815d pnative fsclose
80481ac pnative mmap
8048140 pnative halt
80480b7 pnative clear
80480a9 pnative reset
804c120 pconstant h
804c124 pconstant dp
80481ff pnative exit
80481d8 pnative (literal)
80481e7 pnative (sliteral)
804820e pnative (do)
8048222 pnative (loop)
8048247 pnative (+loop)
804824d pnative r@
804826a pnative r>
804825a pnative >r
804827a pnative i
8048287 pnative j
8048294 pnative +
80482a0 pnative -
80482ae pnative *
80480f8 pnative (if)
80480ed pnative (else)
80482ba pnative /mod
80482ce pnative u/mod
80482e3 pnative and
80482f2 pnative or
8048301 pnative xor
8048310 pnative swap
804831c pnative drop
8048326 pnative dup
8048330 pnative over
804833e pnative =
804835c pnative >
804836c pnative <
804c12c pconstant tib
804837c pnative s@
8048388 pnative lshift
8048396 pnative rshift
80483a4 pnative rshifta
80483b2 pnative execute
80483c0 pnative unloop
80483cc pnative cmove
80483e0 pnative cmove>
c:(variable) @ pnative (variable)
c:(constant) @ pnative (constant)
c:(:) @ pnative (:)
80480d7 pnative (does)
804c128 pconstant heaptop
8048080 pconstant _start
8048418 pconstant _end
80483fb pnative cas
here plastprim !
c:(deferred) @ pnative (deferred)
here pdictbase @ - pdictsize !
pddp @ preloc initmdp
mdictbase @ dictbase @ - dictoffset !
89d7528 stackbase !
decimal
