\ GENERATED BY gen-x.f
include cross.f
hex
1020 textaddr !
3f8 textsize !
2000 pdictaddr !
2398 dictbase !
98e114 theaptop !
20 constant textoffset
create .text textsize @ allot align
.text textsize @ textoffset load.text boot/ff-i386-plan9
11cb c:(variable) !
11d8 c:(constant) !
1065 c:(:) !
13c6 c:(deferred) !
here pdictbase !
10ad pnative @
10b8 pnative !
10c4 pnative c@
10d3 pnative c!
1148 pnative fsread
1171 pnative fswrite
119a pnative fsseek
10fc pnative fsopen
112c pnative fsclose
11bd pnative mmap
10e0 pnative halt
1057 pnative clear
1049 pnative reset
4d5c pconstant h
4d60 pconstant dp
120c pnative exit
11e5 pnative (literal)
11f4 pnative (sliteral)
121b pnative (do)
122f pnative (loop)
1254 pnative (+loop)
125a pnative r@
1277 pnative r>
1267 pnative >r
1287 pnative i
1294 pnative j
12a1 pnative +
12ad pnative -
12bb pnative *
1098 pnative (if)
108d pnative (else)
12c7 pnative /mod
12db pnative u/mod
12f0 pnative and
12ff pnative or
130e pnative xor
131d pnative swap
1329 pnative drop
1333 pnative dup
133d pnative over
134b pnative =
1369 pnative >
1379 pnative <
4d68 pconstant tib
1389 pnative s@
1395 pnative lshift
13a3 pnative rshift
13b1 pnative rshifta
13bf pnative execute
13cd pnative unloop
13d9 pnative cmove
13ed pnative cmove>
c:(variable) @ pnative (variable)
c:(constant) @ pnative (constant)
c:(:) @ pnative (:)
1077 pnative (does)
4d64 pconstant heaptop
1020 pconstant _start
1418 pconstant _end
1408 pnative cas
here plastprim !
c:(deferred) @ pnative (deferred)
here pdictbase @ - pdictsize !
pddp @ preloc initmdp
mdictbase @ dictbase @ - dictoffset !
990114 stackbase !
decimal
